#ifndef BWC_BULLET_H
#define BWC_BULLET_H

#include <stdint.h>

enum bwc_bullet_type {
    BWC_BULLET_MELEE = 0,

    BWC_BULLET_FUSION_CUTTER_HIT = 141,
    BWC_BULLET_GAUSS_RIFLE_HIT,
    BWC_BULLET_C_10_CANISTER_RIFLE_HIT,
    BWC_BULLET_GEMINI_MISSILES,
    BWC_BULLET_FRAGMENTATION_GRENADE,
    BWC_BULLET_LONGBOLT_MISSILE,
    BWC_BULLET_UNUSED_LOCKDOWN,
    BWC_BULLET_ATS_ATA_LASER_BATTERY,
    BWC_BULLET_BURST_LASERS,
    BWC_BULLET_ARCLITE_SHOCK_CANNON_HIT,
    BWC_BULLET_EMP_MISSILE,
    BWC_BULLET_DUAL_PHOTON_BLASTERS_HIT,
    BWC_BULLET_PARTICLE_BEAM_HIT,
    BWC_BULLET_ANTI_MATTER_MISSILE,
    BWC_BULLET_PULSE_CANNON,
    BWC_BULLET_PSIONIC_SHOCKWAVE_HIT,
    BWC_BULLET_PSIONIC_STORM,
    BWC_BULLET_YAMATO_GUN,
    BWC_BULLET_PHASE_DISRUPTOR,
    BWC_BULLET_STA_STS_CANNON_OVERLAY,
    BWC_BULLET_SUNKEN_COLONY_TENTACLE,
    BWC_BULLET_VENOM_UNUSED,
    BWC_BULLET_ACID_SPORE,
    BWC_BULLET_PLASMA_DRIP_UNUSED,
    BWC_BULLET_GLAVE_WURM,
    BWC_BULLET_SEEKER_SPORES,
    BWC_BULLET_QUEEN_SPELL_CARRIER,
    BWC_BULLET_PLAGUE_CLOUD,
    BWC_BULLET_CONSUME,
    BWC_BULLET_ENSNARE,
    BWC_BULLET_NEEDLE_SPINE_HIT,
    BWC_BULLET_INVISIBLE,

    BWC_BULLET_OPTICAL_FLARE_GRENADE = 201,
    BWC_BULLET_HALO_ROCKETS,
    BWC_BULLET_SUBTERRANEAN_SPINES,
    BWC_BULLET_CORROSIVE_ACID_SHOT,
    BWC_BULLET_CORROSIVE_ACID_HIT,
    BWC_BULLET_NEUTRON_FLARE,

    BWC_BULLET_NONE = 209,
    BWC_BULLET_UNKNOWN,
    BWC_BULLET_MAX
};

struct bwc_bullet {
    int32_t id;
    int32_t player;
    enum bwc_bullet_type type;
    int32_t source;
    int32_t positionX;
    int32_t positionY;
    double angle;
    double velocityX;
    double velocityY;
    int32_t target;
    int32_t targetPositionX;
    int32_t targetPositionY;
    int32_t removeTimer;
    int8_t exists;
    int8_t isVisible[9];
};

#endif
