#ifndef BWC_UNITDATA_H
#define BWC_UNITDATA_H

#include <stdint.h>

enum bwc_unitdata_type {
    BWC_UNIT_TERRAN_MARINE,
    BWC_UNIT_TERRAN_GHOST,
    BWC_UNIT_TERRAN_VULTURE,
    BWC_UNIT_TERRAN_GOLIATH,
    BWC_UNIT_TERRAN_GOLIATH_TURRET,
    BWC_UNIT_TERRAN_SIEGE_TANK_TANK_MODE,
    BWC_UNIT_TERRAN_SIEGE_TANK_TANK_MODE_TURRET,
    BWC_UNIT_TERRAN_SCV,
    BWC_UNIT_TERRAN_WRAITH,
    BWC_UNIT_TERRAN_SCIENCE_VESSEL,
    BWC_UNIT_HERO_GUI_MONTAG,
    BWC_UNIT_TERRAN_DROPSHIP,
    BWC_UNIT_TERRAN_BATTLECRUISER,
    BWC_UNIT_TERRAN_VULTURE_SPIDER_MINE,
    BWC_UNIT_TERRAN_NUCLEAR_MISSILE,
    BWC_UNIT_TERRAN_CIVILIAN,
    BWC_UNIT_HERO_SARAH_KERRIGAN,
    BWC_UNIT_HERO_ALAN_SCHEZAR,
    BWC_UNIT_HERO_ALAN_SCHEZAR_TURRET,
    BWC_UNIT_HERO_JIM_RAYNOR_VULTURE,
    BWC_UNIT_HERO_JIM_RAYNOR_MARINE,
    BWC_UNIT_HERO_TOM_KAZANSKY,
    BWC_UNIT_HERO_MAGELLAN,
    BWC_UNIT_HERO_EDMUND_DUKE_TANK_MODE,
    BWC_UNIT_HERO_EDMUND_DUKE_TANK_MODE_TURRET,
    BWC_UNIT_HERO_EDMUND_DUKE_SIEGE_MODE,
    BWC_UNIT_HERO_EDMUND_DUKE_SIEGE_MODE_TURRET,
    BWC_UNIT_HERO_ARCTURUS_MENGSK,
    BWC_UNIT_HERO_HYPERION,
    BWC_UNIT_HERO_NORAD_II,
    BWC_UNIT_TERRAN_SIEGE_TANK_SIEGE_MODE,
    BWC_UNIT_TERRAN_SIEGE_TANK_SIEGE_MODE_TURRET,
    BWC_UNIT_TERRAN_FIREBAT,
    BWC_UNIT_SPELL_SCANNER_SWEEP,
    BWC_UNIT_TERRAN_MEDIC,
    BWC_UNIT_ZERG_LARVA,
    BWC_UNIT_ZERG_EGG,
    BWC_UNIT_ZERG_ZERGLING,
    BWC_UNIT_ZERG_HYDRALISK,
    BWC_UNIT_ZERG_ULTRALISK,
    BWC_UNIT_ZERG_BROODLING,
    BWC_UNIT_ZERG_DRONE,
    BWC_UNIT_ZERG_OVERLORD,
    BWC_UNIT_ZERG_MUTALISK,
    BWC_UNIT_ZERG_GUARDIAN,
    BWC_UNIT_ZERG_QUEEN,
    BWC_UNIT_ZERG_DEFILER,
    BWC_UNIT_ZERG_SCOURGE,
    BWC_UNIT_HERO_TORRASQUE,
    BWC_UNIT_HERO_MATRIARCH,
    BWC_UNIT_ZERG_INFESTED_TERRAN,
    BWC_UNIT_HERO_INFESTED_KERRIGAN,
    BWC_UNIT_HERO_UNCLEAN_ONE,
    BWC_UNIT_HERO_HUNTER_KILLER,
    BWC_UNIT_HERO_DEVOURING_ONE,
    BWC_UNIT_HERO_KUKULZA_MUTALISK,
    BWC_UNIT_HERO_KUKULZA_GUARDIAN,
    BWC_UNIT_HERO_YGGDRASILL,
    BWC_UNIT_TERRAN_VALKYRIE,
    BWC_UNIT_ZERG_COCOON,
    BWC_UNIT_PROTOSS_CORSAIR,
    BWC_UNIT_PROTOSS_DARK_TEMPLAR,
    BWC_UNIT_ZERG_DEVOURER,
    BWC_UNIT_PROTOSS_DARK_ARCHON,
    BWC_UNIT_PROTOSS_PROBE,
    BWC_UNIT_PROTOSS_ZEALOT,
    BWC_UNIT_PROTOSS_DRAGOON,
    BWC_UNIT_PROTOSS_HIGH_TEMPLAR,
    BWC_UNIT_PROTOSS_ARCHON,
    BWC_UNIT_PROTOSS_SHUTTLE,
    BWC_UNIT_PROTOSS_SCOUT,
    BWC_UNIT_PROTOSS_ARBITER,
    BWC_UNIT_PROTOSS_CARRIER,
    BWC_UNIT_PROTOSS_INTERCEPTOR,
    BWC_UNIT_HERO_DARK_TEMPLAR,
    BWC_UNIT_HERO_ZERATUL,
    BWC_UNIT_HERO_TASSADAR_ZERATUL_ARCHON,
    BWC_UNIT_HERO_FENIX_ZEALOT,
    BWC_UNIT_HERO_FENIX_DRAGOON,
    BWC_UNIT_HERO_TASSADAR,
    BWC_UNIT_HERO_MOJO,
    BWC_UNIT_HERO_WARBRINGER,
    BWC_UNIT_HERO_GANTRITHOR,
    BWC_UNIT_PROTOSS_REAVER,
    BWC_UNIT_PROTOSS_OBSERVER,
    BWC_UNIT_PROTOSS_SCARAB,
    BWC_UNIT_HERO_DANIMOTH,
    BWC_UNIT_HERO_ALDARIS,
    BWC_UNIT_HERO_ARTANIS,
    BWC_UNIT_CRITTER_RHYNADON,
    BWC_UNIT_CRITTER_BENGALAAS,
    BWC_UNIT_SPECIAL_CARGO_SHIP,
    BWC_UNIT_SPECIAL_MERCENARY_GUNSHIP,
    BWC_UNIT_CRITTER_SCANTID,
    BWC_UNIT_CRITTER_KAKARU,
    BWC_UNIT_CRITTER_RAGNASAUR,
    BWC_UNIT_CRITTER_URSADON,
    BWC_UNIT_ZERG_LURKER_EGG,
    BWC_UNIT_HERO_RASZAGAL,
    BWC_UNIT_HERO_SAMIR_DURAN,
    BWC_UNIT_HERO_ALEXEI_STUKOV,
    BWC_UNIT_SPECIAL_MAP_REVEALER,
    BWC_UNIT_HERO_GERARD_DUGALLE,
    BWC_UNIT_ZERG_LURKER,
    BWC_UNIT_HERO_INFESTED_DURAN,
    BWC_UNIT_SPELL_DISRUPTION_WEB,
    BWC_UNIT_TERRAN_COMMAND_CENTER,
    BWC_UNIT_TERRAN_COMSAT_STATION,
    BWC_UNIT_TERRAN_NUCLEAR_SILO,
    BWC_UNIT_TERRAN_SUPPLY_DEPOT,
    BWC_UNIT_TERRAN_REFINERY,
    BWC_UNIT_TERRAN_BARRACKS,
    BWC_UNIT_TERRAN_ACADEMY,
    BWC_UNIT_TERRAN_FACTORY,
    BWC_UNIT_TERRAN_STARPORT,
    BWC_UNIT_TERRAN_CONTROL_TOWER,
    BWC_UNIT_TERRAN_SCIENCE_FACILITY,
    BWC_UNIT_TERRAN_COVERT_OPS,
    BWC_UNIT_TERRAN_PHYSICS_LAB,
    BWC_UNIT_UNUSED_TERRAN1,
    BWC_UNIT_TERRAN_MACHINE_SHOP,
    BWC_UNIT_UNUSED_TERRAN2,
    BWC_UNIT_TERRAN_ENGINEERING_BAY,
    BWC_UNIT_TERRAN_ARMORY,
    BWC_UNIT_TERRAN_MISSILE_TURRET,
    BWC_UNIT_TERRAN_BUNKER,
    BWC_UNIT_SPECIAL_CRASHED_NORAD_II,
    BWC_UNIT_SPECIAL_ION_CANNON,
    BWC_UNIT_POWERUP_URAJ_CRYSTAL,
    BWC_UNIT_POWERUP_KHALIS_CRYSTAL,
    BWC_UNIT_ZERG_INFESTED_COMMAND_CENTER,
    BWC_UNIT_ZERG_HATCHERY,
    BWC_UNIT_ZERG_LAIR,
    BWC_UNIT_ZERG_HIVE,
    BWC_UNIT_ZERG_NYDUS_CANAL,
    BWC_UNIT_ZERG_HYDRALISK_DEN,
    BWC_UNIT_ZERG_DEFILER_MOUND,
    BWC_UNIT_ZERG_GREATER_SPIRE,
    BWC_UNIT_ZERG_QUEENS_NEST,
    BWC_UNIT_ZERG_EVOLUTION_CHAMBER,
    BWC_UNIT_ZERG_ULTRALISK_CAVERN,
    BWC_UNIT_ZERG_SPIRE,
    BWC_UNIT_ZERG_SPAWNING_POOL,
    BWC_UNIT_ZERG_CREEP_COLONY,
    BWC_UNIT_ZERG_SPORE_COLONY,
    BWC_UNIT_UNUSED_ZERG1,
    BWC_UNIT_ZERG_SUNKEN_COLONY,
    BWC_UNIT_SPECIAL_OVERMIND_WITH_SHELL,
    BWC_UNIT_SPECIAL_OVERMIND,
    BWC_UNIT_ZERG_EXTRACTOR,
    BWC_UNIT_SPECIAL_MATURE_CHRYSALIS,
    BWC_UNIT_SPECIAL_CEREBRATE,
    BWC_UNIT_SPECIAL_CEREBRATE_DAGGOTH,
    BWC_UNIT_UNUSED_ZERG2,
    BWC_UNIT_PROTOSS_NEXUS,
    BWC_UNIT_PROTOSS_ROBOTICS_FACILITY,
    BWC_UNIT_PROTOSS_PYLON,
    BWC_UNIT_PROTOSS_ASSIMILATOR,
    BWC_UNIT_UNUSED_PROTOSS1,
    BWC_UNIT_PROTOSS_OBSERVATORY,
    BWC_UNIT_PROTOSS_GATEWAY,
    BWC_UNIT_UNUSED_PROTOSS2,
    BWC_UNIT_PROTOSS_PHOTON_CANNON,
    BWC_UNIT_PROTOSS_CITADEL_OF_ADUN,
    BWC_UNIT_PROTOSS_CYBERNETICS_CORE,
    BWC_UNIT_PROTOSS_TEMPLAR_ARCHIVES,
    BWC_UNIT_PROTOSS_FORGE,
    BWC_UNIT_PROTOSS_STARGATE,
    BWC_UNIT_SPECIAL_STASIS_CELL_PRISON,
    BWC_UNIT_PROTOSS_FLEET_BEACON,
    BWC_UNIT_PROTOSS_ARBITER_TRIBUNAL,
    BWC_UNIT_PROTOSS_ROBOTICS_SUPPORT_BAY,
    BWC_UNIT_PROTOSS_SHIELD_BATTERY,
    BWC_UNIT_SPECIAL_KHAYDARIN_CRYSTAL_FORM,
    BWC_UNIT_SPECIAL_PROTOSS_TEMPLE,
    BWC_UNIT_SPECIAL_XELNAGA_TEMPLE,
    BWC_UNIT_RESOURCE_MINERAL_FIELD,
    BWC_UNIT_RESOURCE_MINERAL_FIELD_TYPE_2,
    BWC_UNIT_RESOURCE_MINERAL_FIELD_TYPE_3,
    BWC_UNIT_UNUSED_CAVE,
    BWC_UNIT_UNUSED_CAVE_IN,
    BWC_UNIT_UNUSED_CANTINA,
    BWC_UNIT_UNUSED_MINING_PLATFORM,
    BWC_UNIT_UNUSED_INDEPENDANT_COMMAND_CENTER,
    BWC_UNIT_SPECIAL_INDEPENDANT_STARPORT,
    BWC_UNIT_UNUSED_INDEPENDANT_JUMP_GATE,
    BWC_UNIT_UNUSED_RUINS,
    BWC_UNIT_UNUSED_KHAYDARIN_CRYSTAL_FORMATION,
    BWC_UNIT_RESOURCE_VESPENE_GEYSER,
    BWC_UNIT_SPECIAL_WARP_GATE,
    BWC_UNIT_SPECIAL_PSI_DISRUPTER,
    BWC_UNIT_UNUSED_ZERG_MARKER,
    BWC_UNIT_UNUSED_TERRAN_MARKER,
    BWC_UNIT_UNUSED_PROTOSS_MARKER,
    BWC_UNIT_SPECIAL_ZERG_BEACON,
    BWC_UNIT_SPECIAL_TERRAN_BEACON,
    BWC_UNIT_SPECIAL_PROTOSS_BEACON,
    BWC_UNIT_SPECIAL_ZERG_FLAG_BEACON,
    BWC_UNIT_SPECIAL_TERRAN_FLAG_BEACON,
    BWC_UNIT_SPECIAL_PROTOSS_FLAG_BEACON,
    BWC_UNIT_SPECIAL_POWER_GENERATOR,
    BWC_UNIT_SPECIAL_OVERMIND_COCOON,
    BWC_UNIT_SPELL_DARK_SWARM,
    BWC_UNIT_SPECIAL_FLOOR_MISSILE_TRAP,
    BWC_UNIT_SPECIAL_FLOOR_HATCH,
    BWC_UNIT_SPECIAL_UPPER_LEVEL_DOOR,
    BWC_UNIT_SPECIAL_RIGHT_UPPER_LEVEL_DOOR,
    BWC_UNIT_SPECIAL_PIT_DOOR,
    BWC_UNIT_SPECIAL_RIGHT_PIT_DOOR,
    BWC_UNIT_SPECIAL_FLOOR_GUN_TRAP,
    BWC_UNIT_SPECIAL_WALL_MISSILE_TRAP,
    BWC_UNIT_SPECIAL_WALL_FLAME_TRAP,
    BWC_UNIT_SPECIAL_RIGHT_WALL_MISSILE_TRAP,
    BWC_UNIT_SPECIAL_RIGHT_WALL_FLAME_TRAP,
    BWC_UNIT_SPECIAL_START_LOCATION,
    BWC_UNIT_POWERUP_FLAG,
    BWC_UNIT_POWERUP_YOUNG_CHRYSALIS,
    BWC_UNIT_POWERUP_PSI_EMITTER,
    BWC_UNIT_POWERUP_DATA_DISK,
    BWC_UNIT_POWERUP_KHAYDARIN_CRYSTAL,
    BWC_UNIT_POWERUP_MINERAL_CLUSTER_TYPE_1,
    BWC_UNIT_POWERUP_MINERAL_CLUSTER_TYPE_2,
    BWC_UNIT_POWERUP_PROTOSS_GAS_ORB_TYPE_1,
    BWC_UNIT_POWERUP_PROTOSS_GAS_ORB_TYPE_2,
    BWC_UNIT_POWERUP_ZERG_GAS_SAC_TYPE_1,
    BWC_UNIT_POWERUP_ZERG_GAS_SAC_TYPE_2,
    BWC_UNIT_POWERUP_TERRAN_GAS_TANK_TYPE_1,
    BWC_UNIT_POWERUP_TERRAN_GAS_TANK_TYPE_2,

    BWC_UNIT_NONE,
    BWC_UNIT_ALLUNITS,
    BWC_UNIT_MEN,
    BWC_UNIT_BUILDINGS,
    BWC_UNIT_FACTORIES,
    BWC_UNIT_UNKNOWN,
    BWC_UNIT_MAX
};

struct bwc_unitdata {
    int32_t clearanceLevel;
    int32_t id;
    int32_t player;
    enum bwc_unitdata_type type;
    int32_t positionX;
    int32_t positionY;
    double angle;
    double velocityX;
    double velocityY;
    int32_t hitPoints;
    int32_t lastHitPoints;
    int32_t shields;
    int32_t energy;
    int32_t resources;
    int32_t resourceGroup;

    int32_t killCount;
    int32_t acidSporeCount;
    int32_t scarabCount;
    int32_t spiderMineCount;
    int32_t groundWeaponCooldown;
    int32_t airWeaponCooldown;
    int32_t spellCooldown;
    int32_t defenseMatrixPoints;

    int32_t defenseMatrixTimer;
    int32_t ensnareTimer;
    int32_t irradiateTimer;
    int32_t lockdownTimer;
    int32_t maelstromTimer;
    int32_t orderTimer;
    int32_t plagueTimer;
    int32_t removeTimer;
    int32_t stasisTimer;
    int32_t stimTimer;

    enum bwc_unitdata_type buildType;
    int32_t trainingQueueCount;
    int32_t trainingQueue[5];
    int32_t tech;
    int32_t upgrade;
    int32_t remainingBuildTime;
    int32_t remainingTrainTime;
    int32_t remainingResearchTime;
    int32_t remainingUpgradeTime;
    int32_t buildUnit;

    int32_t target;
    int32_t targetPositionX;
    int32_t targetPositionY;
    int32_t order;
    int32_t orderTarget;
    int32_t orderTargetPositionX;
    int32_t orderTargetPositionY;
    int32_t secondaryOrder;
    int32_t rallyPositionX;
    int32_t rallyPositionY;
    int32_t rallyUnit;
    int32_t addon;
    int32_t nydusExit;
    int32_t powerUp;

    int32_t transport;
    int32_t carrier;
    int32_t hatchery;

    int8_t exists;
    int8_t hasNuke;
    int8_t isAccelerating;
    int8_t isAttacking;
    int8_t isAttackFrame;
    int8_t isBeingGathered;
    int8_t isBlind;
    int8_t isBraking;
    int8_t isBurrowed;
    int32_t carryResourceType;
    int8_t isCloaked;
    int8_t isCompleted;
    int8_t isConstructing;
    int8_t isDetected;
    int8_t isGathering;
    int8_t isHallucination;
    int8_t isIdle;
    int8_t isInterruptible;
    int8_t isInvincible;
    int8_t isLifted;
    int8_t isMorphing;
    int8_t isMoving;
    int8_t isParasited;
    int8_t isSelected;
    int8_t isStartingAttack;
    int8_t isStuck;
    int8_t isTraining;
    int8_t isUnderStorm;
    int8_t isUnderDarkSwarm;
    int8_t isUnderDWeb;
    int8_t isPowered;
    int8_t isVisible[9];
    int32_t buttonset;

    int32_t lastAttackerPlayer;
    int8_t recentlyAttacked;
    int32_t replayID;
};

#endif
