#ifndef BWC_UNITCOMMAND_H
#define BWC_UNITCOMMAND_H

#include <stdint.h>

enum bwc_unitcommand_type {
    BWC_UNITCOMMAND_ATTACK_MOVE,
    BWC_UNITCOMMAND_ATTACK_UNIT,
    BWC_UNITCOMMAND_BUILD,
    BWC_UNITCOMMAND_BUILD_ADDON,
    BWC_UNITCOMMAND_TRAIN,
    BWC_UNITCOMMAND_MORPH,
    BWC_UNITCOMMAND_RESEARCH,
    BWC_UNITCOMMAND_UPGRADE,
    BWC_UNITCOMMAND_SET_RALLY_POSITION,
    BWC_UNITCOMMAND_SET_RALLY_UNIT,
    BWC_UNITCOMMAND_MOVE,
    BWC_UNITCOMMAND_PATROL,
    BWC_UNITCOMMAND_HOLD_POSITION,
    BWC_UNITCOMMAND_STOP,
    BWC_UNITCOMMAND_FOLLOW,
    BWC_UNITCOMMAND_GATHER,
    BWC_UNITCOMMAND_RETURN_CARGO,
    BWC_UNITCOMMAND_REPAIR,
    BWC_UNITCOMMAND_BURROW,
    BWC_UNITCOMMAND_UNBURROW,
    BWC_UNITCOMMAND_CLOAK,
    BWC_UNITCOMMAND_DECLOAK,
    BWC_UNITCOMMAND_SIEGE,
    BWC_UNITCOMMAND_UNSIEGE,
    BWC_UNITCOMMAND_LIFT,
    BWC_UNITCOMMAND_LAND,
    BWC_UNITCOMMAND_LOAD,
    BWC_UNITCOMMAND_UNLOAD,
    BWC_UNITCOMMAND_UNLOAD_ALL,
    BWC_UNITCOMMAND_UNLOAD_ALL_POSITION,
    BWC_UNITCOMMAND_RIGHT_CLICK_POSITION,
    BWC_UNITCOMMAND_RIGHT_CLICK_UNIT,
    BWC_UNITCOMMAND_HALT_CONSTRUCTION,
    BWC_UNITCOMMAND_CANCEL_CONSTRUCTION,
    BWC_UNITCOMMAND_CANCEL_ADDON,
    BWC_UNITCOMMAND_CANCEL_TRAIN,
    BWC_UNITCOMMAND_CANCEL_TRAIN_SLOT,
    BWC_UNITCOMMAND_CANCEL_MORPH,
    BWC_UNITCOMMAND_CANCEL_RESEARCH,
    BWC_UNITCOMMAND_CANCEL_UPGRADE,
    BWC_UNITCOMMAND_USE_TECH,
    BWC_UNITCOMMAND_USE_TECH_POSITION,
    BWC_UNITCOMMAND_USE_TECH_UNIT,
    BWC_UNITCOMMAND_PLACE_COP,
    BWC_UNITCOMMAND_NONE,
    BWC_UNITCOMMAND_UNKNOWN,
    BWC_UNITCOMMAND_MAX
};

struct bwc_unitcommand {
    enum bwc_unitcommand_type type;
    int32_t unitIndex;
    int32_t targetIndex;
    int32_t x;
    int32_t y;
    int32_t extra;
};

#endif
